name: 'plato.elements'
description: A collection of HTML5 custom elements, named Plato Elements, built using Polymer.dart.
version: 0.27.20161108
author: Joseph B. Axenroth

dependencies:
  browser: ^0.10.0+2
  polymer: ^1.0.0-rc.18
  polymer_elements: ^1.0.0-rc.9
  polymer_interop: ^1.0.0-rc.10
  reflectable: ^0.5.4
  web_components: ^0.12.3

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
